### ISSUE TITLE
Internship?

### ISSUE THREAD

**Issue by yych42** [VIkill33/PersonalGPT#2]
Your v2ex activity led me here. Cool project! Especially the UI.

We are looking for an intern iOS dev. You will be working on a new iOS project to get started, but we are looking for someone who can work on several LLM-related products in the future. Are you interested?

**Comment by VIkill33** [comment]
Yes, it sounds great to me. Could you kindly give me your contact, so I can learn more about the job?

**Comment by VIkill33** [comment]
Yes, it sounds great to me. Could you kindly give me your contact, so I can learn more about the job?------------------ Original ------------------From: yych42  ***@***.***>Date: Fri,May 26,2023 7:08 PMTo: VIkill33/PersonalGPT ***@***.***>Cc: Subscribed ***@***.***>Subject: Re: [VIkill33/PersonalGPT] Internship? (Issue #2)
Your v2ex activity led me here. Cool project! Especially the UI.
We are looking for an intern iOS dev. You will be working on a new iOS project to get started, but we are looking for someone who can work on several LLM-related products in the future. Are you interested?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/VIkill33/PersonalGPT/issues/2",
"url": "https://github.com/VIkill33/PersonalGPT/issues/2",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by VIkill33** [comment]
Yes, it sounds great to me. Could you kindly give me your contact, so I can learn more about the job?

**Comment by yych42** [comment]
> Yes, it sounds great to me. Could you kindly give me your contact, so I can learn more about the job?

you can reach me at [removed]
